#!/bin/sh
# cross.env
PREFIX=/usr
TARGET=i586-mingw32msvc
export CC="i586-mingw32msvc-gcc -mms-bitfields"
export CXX="i586-mingw32msvc-g++ -mms-bitfields"
export CFLAGS="-O2 -march=i586 -mms-bitfields"
export CXXFLAGS="-O2 -march=i586 -mms-bitfields"
export PKG_CONFIG_PATH=$PREFIX/$TARGET/lib/pkgconfig
export PATH=$PREFIX/bin:$PREFIX/$TARGET/bin:/bin:/usr/bin
export LD_LIBRARY_PATH=$PREFIX/$TARGET/lib
export LDFLAGS=-L$PREFIX/$TARGET/lib
export OBJDUMP=$PREFIX/bin/objdump
export HOST_CC=/usr/bin/gcc

make