/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <string.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *hbox1;
  GtkWidget *table1;
  //GPtrArray *gparray=g_ptr_array_new();
  ////GtkWidget *board[7][7];
  gboolean fill[7][7]={{FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE},
                       {FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE},
                       {TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE},
                       {TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE},
                       {TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE},
                       {FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE},
                       {FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE}};
  unsigned int i,j;
  
  GtkWidget *b1_3;
  GtkWidget *b1_4;
  GtkWidget *b1_5;
  GtkWidget *b2_3;
  GtkWidget *b2_4;
  GtkWidget *b2_5;
  GtkWidget *b3_3;
  GtkWidget *b3_4;
  GtkWidget *b3_5;
  GtkWidget *b4_1;
  GtkWidget *b4_2;
  GtkWidget *b4_3;
  GtkWidget *b4_5;
  GtkWidget *b4_6;
  GtkWidget *b4_7;
  GtkWidget *b5_1;
  GtkWidget *b5_2;
  GtkWidget *b5_3;
  GtkWidget *b5_5;
  GtkWidget *b5_6;
  GtkWidget *b5_7;
  GtkWidget *b5_4;
  GtkWidget *b3_1;
  GtkWidget *b3_2;
  GtkWidget *b3_6;
  GtkWidget *b3_7;
  GtkWidget *b6_3;
  GtkWidget *b6_4;
  GtkWidget *b6_5;
  GtkWidget *b7_3;
  GtkWidget *b7_4;
  GtkWidget *b7_5;
  GtkWidget *b4_4; //*/
  GtkWidget *vbox1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox2;
  GtkWidget *image1;
  GtkWidget *label1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Chinese Checkers"));

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (window1), hbox1);

  table1 = gtk_table_new (7, 7, TRUE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (hbox1), table1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 10);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 2);
  /*char toggleLabel[5];
  for(i=0; j<7; ++i)
   {
   	for(j=0; j<7; ++j)
   	 {
   	  if(shape[i][j])
   	   {
    	   //board[i][j]=gtk_toggle_button_new_with_mnemonic(_("O"));
        g_ptr_array_add(gparray,(gpointer) gtk_toggle_button_new_with_mnemonic(_("O")));
    	   //gtk_widget_show(board[i][j]);
        gtk_widget_show(g_ptr_array_index(gparray,i*7+j));
    	   gtk_table_attach(GTK_TABLE(table1),g_ptr_array_index(gparray,i*7+j),i,i+1,j,j+1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
        g_signal_connect((gpointer) g_ptr_array_index(gparray,i*7+j), "toggled",
                         G_CALLBACK (cell_changed),
                         NULL);
        sprintf(toggleLabel,"b%d_%d",i+1,j+1);
        GLADE_HOOKUP_OBJECT (window1, g_ptr_array_index(gparray,i*7+j), toggleLabel);
        /*if(!fill[i][j])
         {
		  gtk_widget_set_sensitive(board[i][j], FALSE);
          gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(board[i][j]), TRUE);
         }
   	   }
   	  
   	 }
   }//*/

  b1_3 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b1_3);
  gtk_table_attach (GTK_TABLE (table1), b1_3, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b1_4 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b1_4);
  gtk_table_attach (GTK_TABLE (table1), b1_4, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b1_5 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b1_5);
  gtk_table_attach (GTK_TABLE (table1), b1_5, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b2_3 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b2_3);
  gtk_table_attach (GTK_TABLE (table1), b2_3, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b2_4 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b2_4);
  gtk_table_attach (GTK_TABLE (table1), b2_4, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b2_5 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b2_5);
  gtk_table_attach (GTK_TABLE (table1), b2_5, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b3_3 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b3_3);
  gtk_table_attach (GTK_TABLE (table1), b3_3, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b3_4 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b3_4);
  gtk_table_attach (GTK_TABLE (table1), b3_4, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b3_5 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b3_5);
  gtk_table_attach (GTK_TABLE (table1), b3_5, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b4_1 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b4_1);
  gtk_table_attach (GTK_TABLE (table1), b4_1, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b4_2 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b4_2);
  gtk_table_attach (GTK_TABLE (table1), b4_2, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b4_3 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b4_3);
  gtk_table_attach (GTK_TABLE (table1), b4_3, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b4_5 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b4_5);
  gtk_table_attach (GTK_TABLE (table1), b4_5, 4, 5, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b4_6 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b4_6);
  gtk_table_attach (GTK_TABLE (table1), b4_6, 5, 6, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b4_7 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b4_7);
  gtk_table_attach (GTK_TABLE (table1), b4_7, 6, 7, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b5_1 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b5_1);
  gtk_table_attach (GTK_TABLE (table1), b5_1, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b5_2 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b5_2);
  gtk_table_attach (GTK_TABLE (table1), b5_2, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b5_3 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b5_3);
  gtk_table_attach (GTK_TABLE (table1), b5_3, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b5_5 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b5_5);
  gtk_table_attach (GTK_TABLE (table1), b5_5, 4, 5, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b5_6 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b5_6);
  gtk_table_attach (GTK_TABLE (table1), b5_6, 5, 6, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b5_7 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b5_7);
  gtk_table_attach (GTK_TABLE (table1), b5_7, 6, 7, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b5_4 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b5_4);
  gtk_table_attach (GTK_TABLE (table1), b5_4, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b3_1 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b3_1);
  gtk_table_attach (GTK_TABLE (table1), b3_1, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b3_2 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b3_2);
  gtk_table_attach (GTK_TABLE (table1), b3_2, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b3_6 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b3_6);
  gtk_table_attach (GTK_TABLE (table1), b3_6, 5, 6, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b3_7 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b3_7);
  gtk_table_attach (GTK_TABLE (table1), b3_7, 6, 7, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b6_3 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b6_3);
  gtk_table_attach (GTK_TABLE (table1), b6_3, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b6_4 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b6_4);
  gtk_table_attach (GTK_TABLE (table1), b6_4, 3, 4, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b6_5 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b6_5);
  gtk_table_attach (GTK_TABLE (table1), b6_5, 4, 5, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b7_3 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b7_3);
  gtk_table_attach (GTK_TABLE (table1), b7_3, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b7_4 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b7_4);
  gtk_table_attach (GTK_TABLE (table1), b7_4, 3, 4, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b7_5 = gtk_toggle_button_new_with_mnemonic (_("O"));
  gtk_widget_show (b7_5);
  gtk_table_attach (GTK_TABLE (table1), b7_5, 4, 5, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  b4_4 = gtk_toggle_button_new_with_mnemonic ("");
  gtk_table_attach (GTK_TABLE (table1), b4_4, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0); 
  gtk_widget_set_sensitive (b4_4, FALSE);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (b4_4), TRUE);
//*/
  vbox1 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 10);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (vbox1), button1, FALSE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox2);

  image1 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox2), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("E_xit"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox2), label1, FALSE, FALSE, 0);
  
  g_signal_connect ((gpointer) b1_3, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b1_4, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b1_5, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b2_3, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b2_4, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b2_5, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b3_3, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b3_4, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b3_5, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b4_1, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b4_2, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b4_3, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b4_5, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  /*g_signal_connect ((gpointer) b4_6, "drag_begin",
                    G_CALLBACK (on_b4_6_drag_begin),
                    (gpointer) );//*/
  g_signal_connect ((gpointer) b4_6, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b4_7, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b5_1, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b5_2, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b5_3, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b5_5, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b5_6, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b5_7, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b5_4, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b3_1, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b3_2, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b3_6, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b3_7, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b6_3, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b6_4, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b6_5, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b7_3, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b7_4, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  g_signal_connect ((gpointer) b7_5, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
  /*g_signal_connect ((gpointer) b4_4, "drag_drop",
                    G_CALLBACK (on_b4_4_drag_drop),
                    (gpointer) );//*/
  g_signal_connect ((gpointer) b4_4, "toggled",
                    G_CALLBACK (cell_changed),
                    (gpointer) table1);
                    //*/
  g_signal_connect ((gpointer) button1, "button_release_event",
                    G_CALLBACK (on_button1_button_release_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, table1, "table1");
  GLADE_HOOKUP_OBJECT (window1, b1_3, "b1_3");
  GLADE_HOOKUP_OBJECT (window1, b1_4, "b1_4");
  GLADE_HOOKUP_OBJECT (window1, b1_5, "b1_5");
  GLADE_HOOKUP_OBJECT (window1, b2_3, "b2_3");
  GLADE_HOOKUP_OBJECT (window1, b2_4, "b2_4");
  GLADE_HOOKUP_OBJECT (window1, b2_5, "b2_5");
  GLADE_HOOKUP_OBJECT (window1, b3_3, "b3_3");
  GLADE_HOOKUP_OBJECT (window1, b3_4, "b3_4");
  GLADE_HOOKUP_OBJECT (window1, b3_5, "b3_5");
  GLADE_HOOKUP_OBJECT (window1, b4_1, "b4_1");
  GLADE_HOOKUP_OBJECT (window1, b4_2, "b4_2");
  GLADE_HOOKUP_OBJECT (window1, b4_3, "b4_3");
  GLADE_HOOKUP_OBJECT (window1, b4_5, "b4_5");
  GLADE_HOOKUP_OBJECT (window1, b4_6, "b4_6");
  GLADE_HOOKUP_OBJECT (window1, b4_7, "b4_7");
  GLADE_HOOKUP_OBJECT (window1, b5_1, "b5_1");
  GLADE_HOOKUP_OBJECT (window1, b5_2, "b5_2");
  GLADE_HOOKUP_OBJECT (window1, b5_3, "b5_3");
  GLADE_HOOKUP_OBJECT (window1, b5_5, "b5_5");
  GLADE_HOOKUP_OBJECT (window1, b5_6, "b5_6");
  GLADE_HOOKUP_OBJECT (window1, b5_7, "b5_7");
  GLADE_HOOKUP_OBJECT (window1, b5_4, "b5_4");
  GLADE_HOOKUP_OBJECT (window1, b3_1, "b3_1");
  GLADE_HOOKUP_OBJECT (window1, b3_2, "b3_2");
  GLADE_HOOKUP_OBJECT (window1, b3_6, "b3_6");
  GLADE_HOOKUP_OBJECT (window1, b3_7, "b3_7");
  GLADE_HOOKUP_OBJECT (window1, b6_3, "b6_3");
  GLADE_HOOKUP_OBJECT (window1, b6_4, "b6_4");
  GLADE_HOOKUP_OBJECT (window1, b6_5, "b6_5");
  GLADE_HOOKUP_OBJECT (window1, b7_3, "b7_3");
  GLADE_HOOKUP_OBJECT (window1, b7_4, "b7_4");
  GLADE_HOOKUP_OBJECT (window1, b7_5, "b7_5");
  GLADE_HOOKUP_OBJECT (window1, b4_4, "b4_4");//*/
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");

  return window1;
}

